version: '3.4'

services:

#//LD DATABASE IN SEPARATED CONTAINER, Can be called from any other container
  sql.data:
    image: microsoft/mssql-server-linux:latest
    container_name: sql_database
    environment:
    - SA_PASSWORD=Pass@word
    - ACCEPT_EULA=Y
    ports:
    - "5433:1433"
# inspect the IP of this db -> docker inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}" sql_database
# how to connect from management studio: localhost,5444 - Pass@word

  crudapi:
    image: crudapi
    container_name: crud_api
    build:
      context: ./crudapi
      dockerfile: Dockerfile
    depends_on:
      - sql.data #depend on the DATABASE service 


#// THIS IS A WEB APP, AT THE MOMENT I'M NOT RUNNING THE CONTAINER FOR THIS PROJECT
#  eshopweb:
#    image: eshop/web
#    build:
#      context: ./eShopWeb
#      dockerfile: Dockerfile
#    depends_on:
#      - sql.data #depend on the DATABASE service

#EXAMPLES ON HOW TO CONSUME ENDPOINTS WITH THIS CONFIGURATION
#   http://localhost:32776/api/persons/getPersons
#   http://localhost:32776/api/persons/addPerson

#EXAMPLE ON HOW TO DO THE SAME FOR THE SAME PROJECT IF I DO NOT RUN UNDER CONTAINERS
#   http://localhost:61724/api/persons/getPersons (this is the port I have in launchSettings.json)
#   http://localhost:61724/api/persons/addPerson (this is the port I have in launchSettings.json)