version: '3.4'

services:
#//LD WEB APP
  eshopweb:
    image: eshop/web
    build:
      context: ./eShopWeb
      dockerfile: Dockerfile
    depends_on:
      - sql.data #depend on the DATABASE service we create

#//LD DATABASE IN SEPARATED CONTAINER CALLED BY THE MVC APP
  sql.data:
    image: microsoft/mssql-server-linux:latest
    environment:
    - SA_PASSWORD=Pass@word
    - ACCEPT_EULA=Y
    ports:
    - "5434:1433"


  crudapi:
    image: crudapi
    build:
      context: ./crudapi
      dockerfile: Dockerfile
